### ISSUE TITLE
Error caused by the "disable" property in blend.json

### ISSUE THREAD

**Issue by yuanchuan** [yoksel/svg-filters#1]
![image](https://user-images.githubusercontent.com/250426/44611535-37a31300-a834-11e8-95fc-1d36dadda17f.png)

-----------------------

### Probably workaround:

Return an empty object here or filter null values for the `propsList` outside:
https://github.com/yoksel/svg-filters/blob/master/src/components/Docs/index.js#L34

ps:  Thanks for making this tool :)

**Comment by yoksel** [comment]
Fixed, thank you : )
