### ISSUE TITLE
Change foto

### ISSUE THREAD

**Issue by elalemanyo** [yoksel/svg-filters#2]
Would be great to make possible to use own images, maybe to make it simple just make possible to change url from img tag, so the image need to be hosted and not upload needed.

Thanks for this great tool.

**Comment by yoksel** [comment]
@elalemanyo  You can do it this way:

1. Click **Your Code**, then **Add**
   ![screen shot 2018-11-28 at 13 54 28](https://user-images.githubusercontent.com/2571308/49147258-3e4e9400-f315-11e8-9f64-ca52979bf525.png)

2. Click **Add example** (or just add your own code)
   ![screen shot 2018-11-28 at 13 54 40](https://user-images.githubusercontent.com/2571308/49147263-40b0ee00-f315-11e8-8b1e-b6f7dd609a83.png)

3.  Change image url in code. Edit code if you need
   ![screen shot 2018-11-28 at 13 54 56](https://user-images.githubusercontent.com/2571308/49147266-43134800-f315-11e8-9f2b-9c71d2852d5b.png)

I hope it helps

**Comment by elalemanyo** [comment]
True! Sorry I didn't saw the feature 😞
Thanks for this great tool!
